### ISSUE TITLE
Example is not working in latest release

### ISSUE THREAD

**Issue by pasviegas** [RobotlegsJS/RobotlegsJS-Pixi#13]
I don't know if you guys noticed but the example doesn't seem to be working anymore after last release.

It seems like the mediator is not initialized.

I am probably doing this wrong, but if I change  
```ts
// ContainerRegistry.ts
public findParentBinding(target: any): ContainerBinding {
        let parent: any = target.parent;
        while (parent) {
            const binding: ContainerBinding = this._bindingByContainer.get(
                parent
            );
            if (binding) {
                return binding;
            }
            parent = parent.parent;
        }
        return null;
    }
```

to 

```ts
// ContainerRegistry.ts
public findParentBinding(target: any): ContainerBinding {
        let parent: any = target.parent;
        while (parent) {
            const binding: ContainerBinding = this._bindingByContainer.get(
                parent
            );
            if (binding) {
                return binding;
            }
            parent = parent.parent;
        }
        return this.rootBindings[0];
    }
```

It works.

Best

**Comment by tiagoschenkel** [comment]
The usage of the **const** declaration inside the **while** loop appears to be wrong, since it should be a **let** declaration.

Let me write some unit tests for the version before we applied the changes and see if I can catch what is not working anymore.

**Comment by pasviegas** [comment]
Nice! Thanks! :D

**Comment by tiagoschenkel** [comment]
The pull request #17 solves this issue. A new version will be released soon.

**Comment by tiagoschenkel** [comment]
Problem not solved yet, still investigating, :(

**Comment by tiagoschenkel** [comment]
Release [0.0.6](https://github.com/RobotlegsJS/RobotlegsJS-Pixi/releases/tag/0.0.6) solves this issue.
