### ISSUE TITLE
Clean _mediators array in MediatorFactory

### ISSUE THREAD

**Issue by pasviegas** [RobotlegsJS/RobotlegsJS-Pixi#14]
Hey guys!

Right now the mediators array in MediatorFactory is not releasing any view instance that the application create, and with time it starts to be very memory consuming.

Is there a way to clean it? Or maybe would it be possible to have it automatically cleaned?

Thanks

**Comment by pasviegas** [comment]
After digging a little bit, the issue seems to be with removeChildren, I don't think this function is patched the same way as removeChild

**Comment by tiagoschenkel** [comment]
@endel, can you take a look?

**Comment by tiagoschenkel** [comment]
Release [0.0.6](https://github.com/RobotlegsJS/RobotlegsJS-Pixi/releases/tag/0.0.6) solves this issue.
